apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world-task
            image: rsharoni/hello-world:1.0.0
            args:
            - /bin/sh
            - -c
            - echo "CronJob executed at $(date)"
          restartPolicy: OnFailure
