apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Keep this empty to match your PVC's blank StorageClass
  hostPath:
    path: /data  
    # <-- folder on your computer

