apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # required for hostPath PVs in Minikube
  resources:
    requests:
      storage: 1Gi
